version: "3"

services:
  rabbitmq:
    image: masstransit/rabbitmq
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbit-net

volumes:
  rabbit-data:

networks:
  rabbit-net:
